### ISSUE TITLE
TEAMS: Use user_candidates api endpoint to fetch team member candidates

### ISSUE THREAD

**Issue by lkleisa** [puzzle-bbt/bbt#110]
For encryptable file sharing, we need possible candidates, which could receive the shared file.

Fetching those candidates quite similar to fetching candidates for team member.

so the idea is to use the same endpoint to fetch encryptable sharing recipients or possible team members.

### ToDo

- [ ] Create UserCandidatesController
  - [ ] Create a UserCandidatesControllerSpec and add all test cases (get inspired by given  teams/candidates_controller spec)
  - [ ] Update route in routes/api.rb to new controller
  - [ ] Add new UserCandidatesPolicy for index method, User::Api should not be allowed to use this endpoint
  - [ ] Move logic from teams/candidates_controller until new specs are passing
    - [ ] Check if team_id.present? (must be present for now)
    - [ ] If yes, return team.memeber_candidates (old code)
    - [ ] ~If not, return User::Human.where.not(id: current_user.id)~ later when adjusting endpoint for new feature
    - [ ] create and use UserMinimalSerializer, attrs: id, username, givenname, surname
- [ ] remove all existing teams/candidates code (controller, spec, ...)
- [ ] switch frontend to use new endpoint for fetching team member candidates
- [ ] make sure username is also shown in list
