### ISSUE TITLE
Wekan Projekt mit Taiga Projekt vergleichen

### ISSUE THREAD

**Issue by tuxmatta** [puzzle-bbt/bbt#163]
Überprüfen, ob alle Inhalte vom Wekan Projekt ins Taiga übernommen worden sind. Differenzen in einem neuen Issue dokumentieren.

**Comment by Eggimpa** [comment]
Funktioniert bei folgenden Eigenschaften: 
## Userstories:
- Die Userstorries werden mit richtigem Namen erstellt
- Die Userstorries werden in die Richtige Swimlane eingeordnet
- Die Assignees sind richtig gesetzt 
- Labels werden gesetzt
- Description wird gesetzt

## Subtasks
- die Subtasks werden erstellt
- Tags werden gesetzt 
- Assignee wird gesetzt 
- Watcher werden gesetzt
- Checklisten werden erstellt 
- Comments werden erstellt

Funktioniert nicht:

##Userstory:

- [ ] Watchers werden nicht gesetzt
- [ ] Attachements werden nicht erstellt
- [ ] Comments werden nicht erstellt
- [ ] Due Date wird nicht gesetzt

## Subtasks
- [ ] DueDate wird nicht gesetzt 
- [ ] Assignee wird gesetzt wenn keiner sein sollte (ThisIsAnotherSubtask)


## Neues Issue wurde erstellt
