### ISSUE TITLE
Fehler aus Test- Migration beheben

### ISSUE THREAD

**Issue by Eggimpa** [puzzle-bbt/bbt#183]
Aufgetretene Fehler bei Migration eines kleinen Projekts beheben. In diesem Kleinen Projekt sind alle Fälle abgedekt von nun an mit diesem Arbeiten. 

 # Funktioniert bei folgenden Eigenschaften: 
## Userstories:
- Die Userstorries werden mit richtigem Namen erstellt
- Die Userstorries werden in die Richtige Swimlane eingeordnet
- Die Assignees sind richtig gesetzt 
- Labels werden gesetzt
- Description wird gesetzt

## Subtasks
- die Subtasks werden erstellt
- Tags werden gesetzt 
- Assignee wird gesetzt 
- Watcher werden gesetzt
- Checklisten werden erstellt 
- Comments werden erstellt
- Descriptions werden erstellt

# Funktioniert nicht:

## Userstory:

- [x] Watchers werden nicht gesetzt
- [x] Attachements werden nicht erstellt
- [x] Comments werden nicht erstellt
- [x] Due Date wird nicht gesetzt
- [x] Atttachment wird an jede Story gehängt
- [ ] Statuse werden nicht richtig gesetzt 

## Subtasks
- [x] DueDate wird nicht gesetzt 
- [x] Assignee wird gesetzt wenn keiner sein sollte (ThisIsAnotherSubtask)
- [x] Es werden immer alle Subtasks gesetzt und nicht nur die richtigen. 
- [ ] Attachements werden jedem Subtask angehängt

## Label
Es handelt sich um Fehler die bei der Testmigration entdeckt wurden.
