### ISSUE TITLE
Subtask und UserStory zusammennehmen

### ISSUE THREAD

**Issue by Vakmeth** [puzzle-bbt/bbt#222]
Im Moment ist der SubtaskProcessor ein Abbild des UserstoryProcessors. Ändern wir etwas im UserstoryProcessor muss es auch im SubtaskProcessor geändert werden. Dies ist umständlich und nicht schön, weswegen wir die zwei Klassen zusammennehmen wollen.

- [x] MigrationProcessor in interface umwandeln
- [x] Models zusammenführen (wenn nötig mit parent Klasse)
- [x] Parent Processor für UserStoryProcessor und SubtaskProcessor
- [x] Tests aktualisieren und ergänzen wo nötig

**Comment by lkleisa** [comment]
Ich habe die beiden Models Subtask und Userstory entfernt und ein Model Task erstellt. Dazu auch die beiden Processor SubTask und UserStory zusammengeführt in einen TaskProcessor. 
Alle Models Userstory und Subtask sind jetzt vom Typ task und beinhalten eigentlich die genau gleichen Attribute. Der Unterschied: Userstories haben mehrere Attribute gesetzt, welche bei subtask null oder leer sind. 
Die tests sind fast alle aktualisiert, jedoch funktionieren noch nicht alle
