### ISSUE TITLE
Vorbereitung Vorträge Eltern-Abend

### ISSUE THREAD

**Issue by mtnstar** [puzzle-bbt/bbt#361]
Vorbereitung für die Vorträge am Elternabend.

Dauer Vortrag: 15-20min, ohne anschliessende Fragerunde

Teams:

- Marc und Lias
- Yanick und Niklas

# ToDo

- [ ] Thema festlegen und von @mtnstar absegnen lassen
- [ ] Erstellen des Inhaltsverzeichnisses, mit @mtnstar kurz besprechen/syncen
- [ ] Ausarbeiten der Folien sowie der Inhalte
