### ISSUE TITLE
IT-Ninjas Oktober 2024 vorbereiten

### ISSUE THREAD

**Issue by ManuelMoeri** [puzzle-bbt/bbt#371]
### TODO
- [x] Alle beteiligten wissen was sie zu tun haben
- [x] Alle Tools & Repos wurden kurz getestet und sind ready
- [x] Nur für Roboter-Posten: Der Posten ist aufgestellt und bereit für die Schnupperlis
- [x] Sämtliche Links zu Posten beschreibungen & ähnliches wurden an einem Ort gesammelt -> Im Codi weiter unten.

### Codi
Hier ist noch das Codi mit den wichtigsten Informationen: https://codimd.puzzle.ch/jzSJu3O8QO-NO2ND2qwvmg?both#Mittwoch
